version: '3.8'

services:
  pdf-generator:
    build: .
    restart: always
    # NOVO MAPEAMENTO: Mapeia a porta 9090 do host (VPS/Coolify) para a porta 8000 do container.
    ports:
      - "9090:8000"
    container_name: pdf_invoice_generator
    environment:
      - PYTHONUNBUFFERED=1